name:
author: 
url: https://avseygames.github.io/
baseurl: 
resume_site: 
description: 
github_username: 
github: 
plugins: [jekyll-paginate]
permalink: /:title
paginate: 6
paginate_path: "/page/:num/"
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
highlighter: rouge
markdown: kramdown
comments :
  gitalk :
    clientID : 
    clientSecret : 
    repo : 
    owner : 
    admin : 
